server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db;
    username: root
    password: dlswjd13
  jpa:
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
